DROP TABLE IF EXISTS SYSTEM_CONFIG;

CREATE TABLE SYSTEM_CONFIG
(
	id BIGINT(20) NOT NULL COMMENT '主键ID',
	key VARCHAR(50) NULL DEFAULT NULL COMMENT 'key',
	value varchar(255) NULL DEFAULT NULL COMMENT 'value',
	remark VARCHAR(255) NULL DEFAULT NULL COMMENT '说明',
	PRIMARY KEY (id)
);