server:
  port: 8080
  servlet:
    context-path: /
# DataSource Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/aurora.sql
    data: classpath:db/aurora-data.sql
    url: jdbc:h2:mem:aurora
    username: root
    password: 666666
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true
